# Usa un'immagine base di Node.js 20
FROM node:20

# Imposta la directory di lavoro all'interno del container
WORKDIR /usr/src/app

# Copia il package.json e il package-lock.json (se presente)
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia il resto del codice dell'applicazione
COPY . .

# Espone la porta su cui gira l'applicazione
EXPOSE 3000

# Comando per avviare l'applicazione
CMD ["node", "api.js"]
